---

- name: Install apt packages
  apt:
    name:
    - git
    - python3-pip
    - curl
    - nmap
    - build-essential
    - libpcap-dev
    - libusb-1.0-0-dev
    - libnetfilter-queue-dev
    update_cache: yes
  become: true

- name: Download Go 1.25.1
  get_url:
    url: https://go.dev/dl/go1.25.1.linux-amd64.tar.gz    
    dest: /tmp/go.tar.gz
  become: true

- name: Remove old Go installation if exists
  file:
    path: /usr/local/go
    state: absent
  become: true

- name: Extract Go
  unarchive:
    src: /tmp/go.tar.gz
    dest: /usr/local
    remote_src: yes
    creates: /usr/local/go/bin/go
  become: true

- name: Create Go workspace directories
  file:
    path: "{{ item }}"
    state: directory
    owner: debian
    group: debian
    mode: '0755'
  loop:
    - /home/debian/go
    - /home/debian/go/bin
    - /home/debian/go/src
    - /home/debian/go/pkg
  become: true

- name: Add Go environment variables to debian profile
  blockinfile:
    path: /home/debian/.profile
    block: |
      export GOROOT=/usr/local/go
      export GOPATH=$HOME/go
      export PATH=$GOROOT/bin:$GOPATH/bin:$PATH
    marker: "# {mark} ANSIBLE MANAGED BLOCK - GO"
    create: yes
    owner: debian
    group: debian
    mode: '0644'
  become: true  

- name: Install Bettercap using Go
  shell: |
    export GOROOT=/usr/local/go
    export GOPATH=/home/debian/go
    export PATH=$GOROOT/bin:$GOPATH/bin:$PATH
    go install github.com/bettercap/bettercap@latest
  args:
    creates: /home/debian/go/bin/bettercap
  become: true
  become_user: debian
  environment:
    HOME: /home/debian

- name: Create bettercap proxies directory
  file:
    path: /home/debian/proxies
    state: directory
    owner: debian
    group: debian
    mode: '0755'
  become: true

- name: Copy bettercap proxies
  copy:
    src: files/
    dest: /home/debian/proxies/
    owner: debian
    group: debian
    mode: '0644'
  become: true

- name: Copy bettercap proxy script
  ansible.builtin.template:
    src: bettercap_proxy.cap
    dest: /home/debian/bettercap_proxy.cap
    owner: debian
    group: debian
    mode: '0644'
